### ISSUE TITLE
 ✍️⚙️Amplify Page: Send email feature - Gmail OAuth 

### ISSUE THREAD

**Issue by manishapriya94** [Ally-Guide/ally-guide-app#32]
### Ask

Hello! 

Looking to implement Oauth for Gmail.

Flow for UI --> 
- User interacts with UI to find Reps + messaging
- Button triggers authorization to create cookie
- Cookie to be used to make call to Gmail API

<img width="1405" alt="Screen Shot 2020-07-21 at 3 55 27 AM" src="https://user-images.githubusercontent.com/23509377/88047209-1d4c3f80-cb06-11ea-9ba5-10dcff498aa0.png">

- **Message button** at the side or top? Open as a new page (we can refine to modal later)
   - At this time they would have a modal to enter in credentials after which they could send the message (pulling from the google civic api to the receiving party's email address)  
- Email subject line should be a combination of the name and template title demand 

### Priority:
- **Medium** --> Turnaround time within a week consult @BeeXiong @hashtagchris for questions

### Context 

Resources to get started:
  - [template/script/style here](https://github.com/Ally-Guide/ally-guide-app/blob/master/ally-guide/src/views/Elevate.vue)
- API Configuration
  - Secrets should be configured in root .env file, configured in index.js file on [server directory](https://github.com/Ally-Guide/ally-guide-app/tree/master/server) 
  - Secrets configured here: 
<img width="558" alt="Screen Shot 2020-07-08 at 2 34 19 PM" src="https://user-images.githubusercontent.com/9143339/86976540-8a87ca00-c12f-11ea-9f61-addd48f6e53b.png">
  - import api call variables here 
<img width="572" alt="Screen Shot 2020-07-08 at 2 34 50 PM" src="https://user-images.githubusercontent.com/9143339/86976538-88257000-c12f-11ea-9ec7-02c8dd483d0a.png"

**Research** 
- [Passport.js Tutorial](https://www.youtube.com/playlist?list=PL4cUxeGkcC9jdm7QX143aMLAqyM-jTZ2x)

### Tasks
- [x] Configure civic api to return rep email addresses
- [ ] oauth config
  - [ ] Back-end Endpoints
    - [ ] Create auth Endpoint in server/routes/api + route endpoints to connect to front-end
      - [ ] Get Endpoint (/auth/google)
    - [ ] Implement [Passport.js](http://www.passportjs.org/packages/passport-oauth2/)
    - [ ] Implement GoogleStrategy using Passport.js
      - [ ] Configure secrets into Heroku Environment
      - [ ] Authorize Users
    - [ ] Create Cookie Session
  - [ ] Front-end
    - [ ] Create Authorize Button in UI + trigger API call to api/auth/google
    - [ ] Notify User of Sign in
- [ ] styling of modal
