### ISSUE TITLE
Phase 1: Feature/Milestones Tracking Issue

### ISSUE THREAD

**Issue by manishapriya94** [Ally-Guide/ally-guide-app#59]
# Purpose 

How can we translate our skills and resources towards racial justice? Ally.Guide is webapp that triages a starting place to collaborate with current racial justice efforts and echo Black Lives Matter through the following programs.  ([current website](www.ally.guide), [GitHub](https://github.com/Ally-Guide/ally-guide-app), [Slack](https://join.slack.com/t/ally-guide/shared_invite/zt-fpx4ach3-OlGutY6lsd7lXKphj8KpAA))

### ⚠️📢 Calling developers, designers, and content writers 
This issue summarizes how we all collaborate together, if you're interested in **[Implementation](https://github.com/Ally-Guide/ally-guide-app/projects/4) (design, frontend, backend)** or **[Content](https://github.com/Ally-Guide/ally-guide-app/projects/5)** (design, content entry and copy), go to the respective boards or contact @manishapriya94 if there any confusion

<table>
  <tr>
   <td><strong>        Educate</strong>
   </td>
   <td><strong>        Circulate</strong>
   </td>
   <td><strong>    Communicate</strong>
   </td>
   <td>
    <strong>Elevate</strong>
   </td>
  </tr>
  <tr>
   <td>Consolidation of knowledge that cater to different learning personas through sections: FAQ, Library, and Learning Paths. 
   </td>
   <td>Ensuring we can complement 501(c)(3) efforts by circulating contributions directly to grassroots organizing and community bail funds.
   </td>
   <td>Amplify issues that trouble our justice system directly to educational, county, local, state, and federal institutions.<strong> </strong>
   </td>
   <td>Contribute intersectionally and create opportunities by supporting existing efforts through your skillset via Events, Community, and Communications. 
   </td>
  </tr>
</table>

 

# Feature Development (Teams + Page) 

### Responsibilities
@ProjectCoordinators (tagged) update these upon deadline extensions/completion. 
@collaborators, check workflow details and status here: 

### Updates/Teams: 
**⚙️Implementation Project Board: 🎨**Design, 🖼Frontend, 🗂Backend

**📖Content Project Board: 🎨**Design,🗃Content Entry, 📝Content Copy 

Status: Planning ✍️, Working 🏗, Reviewing☕️, Stuck 🚧, Done ✅

<table>
  <tr>
   <td><strong>Team<em> (people to reach out to)</em></strong>
   </td>
   <td>

**[Circulate](https://github.com/Ally-Guide/ally-guide-app/issues/70)**
   </td>
   <td>

**[Communicate](https://github.com/Ally-Guide/ally-guide-app/issues/73)**
   </td>
   <td>

**[Educate](https://github.com/Ally-Guide/ally-guide-app/issues/71)**
   </td>
  <td>

**[Elevate](https://github.com/Ally-Guide/ally-guide-app/issues/74)** 
  </td>
  <td><span style="text-decoration:underline;">Volunteering? Let us reach out</span>
  </td>
  </tr>
  <tr>
   <td><strong>🗃Content Entry </strong>

<strong><em>@manishapriya94</em></strong>
</td>
<td> 

- [ ] Add in information to database 
</td>
<td>

- [ ] Add in county and committee information for all 50 states
</td>
<td> 

- [ ] Add in library resources
</td>
<td>

- [ ] Add in database of apprenticeships per city (TechHire)
</td>
<td><a href="https://github.com/github/ally-guide/issues/1">Ally Hour calendar </a>

<a href="https://docs.google.com/document/d/1UwaqEnSUDffWR-KbEKjaMD615i0qDxxCHcmmddKREWE/edit?usp=sharing">Getting started workflow</a>
</td>
</tr>
<tr>
<td><strong>📝 Content Copy</strong>

<strong><em>@ayalabineh @karicunard </em></strong>(Communicate)

<strong><em>@hectorsector</em> </strong>(Edu)
 </td>
 <td>

- [ ] Update descriptions of orgs as needed 
- [ ]  Instructions around use 
 </td>
 <td>

- [ ] State specific message templates 
 </td>
 <td>

- [ ] Org DI&B curriculum template 

- [ ] Learning Paths: Module 1
 </td>
 <td>

- [ ] Weekly check ins

- [ ] Create Blog Guidelines + issue template
</td>
<td>
</td>
</tr>
<tr>
   <td><strong>🎨Design</strong>

<strong><em>@jjjaney</em></strong>
 </td>
 <td>

- [ ] Page display of search, query results, and default 
 </td>
 <td>

- [ ] Accompanying cartoon explaining the story behind each message template.
 </td>
 <td>

- [ ] Learning Path Graphics 

- [ ] FAQ graphics
 </td>
 <td>

- [ ] Add to FAQ graphics for newsletter

- [ ] Style guide for Blog
 </td>
 <td>
 </td>
</tr>
<tr>
   <td><strong>🖼FrontEnd</strong>
<strong><em>@mahrsbar</em></strong>
 </td>
 <td> 

- [ ] Implement card style of records 
</td>

- [ ] <td>Modal for message 

- [ ] Action Options
</td>
<td>

- [ ] LP:Mailchimp email templated

- [ ] Library design<strong> </strong>
</td>
<td>

- [ ] Newsletter and Blog formatted 
</td>
<td>
</td>
</tr>
<tr>
<td><strong>🗂BackEnd</strong>
<strong><em>@beexiong</em></strong>
</td>
<td>

- [ ] API data formatting 

- [ ] Analytics for funds

- [ ] Query optimized 
</td>
<td>

- [ ] OAuth vs mail api 

- [ ] Analytics for whats sent 
</td>
<td>

- [ ] API Data formatting

- [ ] Query for FAQ 
- [ ] Add filters to Library 
 </td>
 <td>

- [ ] Add Blog Page<strong> </strong>
 </td>
 <td>
 </td>
  </tr>
  <tr>
   <td><strong>🤝User feedback</strong>
<strong>@howrad</strong>
<strong><em>@manishapriya94</em></strong>
</td>
<td>

- [x] Issue templates for reporting bugs in page
</td>
<td>

- [ ] Issue templates for reporting bugs in reps 

- [ ] Policy tracking
 </td>
 <td>

- [x] Issue templates for reporting bugs in Library

- [ ] Survey of Learning Paths
 </td>
 <td>templates for reporting bugs 
 </td>
 <td>
 </td>
</tr>
</table>

**Comment by jjjaney** [comment]
@manishapriya94 where does general maintenance fall under? Concerned about technical debt moving forward, as we can be known for ;) 

<img width="850" alt="Screen Shot 2020-07-23 at 1 12 36 PM" src="https://user-images.githubusercontent.com/6806032/88334244-53e0b080-cce6-11ea-8e3e-ceefb71e90b7.png">

<img width="570" alt="Screen Shot 2020-07-23 at 1 12 02 PM" src="https://user-images.githubusercontent.com/6806032/88334249-5511dd80-cce6-11ea-8d32-346e61154261.png">

**Comment by manishapriya94** [comment]
@BeeXiong @teakopp are these areas that one of you would be comfortable leading?
